server:
  port: 8765
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: ADMIN-SERVICE
          uri: lb://ADMIN-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/admin/**
