server :
  port : 8765
spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: USER-SERVICE
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
