server :
  port : 8765
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user-service/**
          filters:
            - RewritePath=/api/user-service/(?<segment>.*), /${segment}
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/admin-service/**
          filters:
            - RewritePath=/api/admin-service/(?<segment>.*), /${segment}
        - id: common-service
          uri: lb://COMMON-SERVICE
          predicates:
            - Path=/api/common-service/**
          filters:
            - RewritePath=/api/common-service/(?<segment>.*), /${segment}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
