eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  common-service:
    endpoints:
      endpoint:
        uri: http://COMMON-SERVICE/**
  hr-operations-service:
    endpoints:
      endpoint:
        uri: http://HR-OPERATIONS-SERVICE/**
  payroll-service:
    endpoints:
      endpoint:
        uri: http://PAYROLL-SERVICE/**
  admin-service:
    endpoints:
      endpoint:
        uri: http://ADMIN-SERVICE/**
