spring:
  application:
    name: COMMON-SERVICE
server :
  port : 8083
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  datasource:
    url: jdbc:mysql://localhost:3306/medilab_DB
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: adityasinghraj0405@gmail.com
    password: cvnpfnumxbajrcsc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

doctor:
  timeslot:
    default-buffer-time: 10
